version: '3.1'

services:

#  db:
#    image: postgres:13
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./docker_volumes/postgresql/data:/var/lib/postgresql/data/pgdata
#
#  omnidb:
#    image: taivokasper/omnidb
#    ports:
#      - 8080:8080
#      - 25482:25482
#    environment:
#      PGADMIN_DEFAULT_EMAIL: root
#      PGADMIN_DEFAULT_PASSWORD: root
#    volumes:
#      - ./docker_volumes/postgresql/omnidb:/etc/omnidb

#  minio:
#    image: minio/minio:RELEASE.2020-06-03T22-13-49Z
#    command: server /data
#    ports:
#      - 9000:9000
#    environment:
#      MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
#      MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
#      MINIO_COMPRESS: "on"
#      MINIO_COMPRESS_EXTENSIONS: ".pdf,.doc,.xml,.xlsx,.png,.txt,.json,.jpeg"
#      MINIO_COMPRESS_MIME_TYPES: "application/pdf"
#    volumes:
#      - ./docker_volumes/minio:/data
#
#  redis:
#    image: redislabs/rejson:latest
#    ports:
#      - 6379:6379

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672